### ISSUE TITLE
你好，有个事请教一下

### ISSUE THREAD

**Issue by t0data** [vvmdx/Sec-Interview-4-2023#8]
Hi，小哥，能联系一下我吗，微博ID：t0data，有个事找你商量一下

**Comment by vvmdx** [comment]
@t0data 微博已留言，但是联系方式留错了...您可以微博回复我下

**Comment by t0data** [comment]
你是访问这个微博吗？https://weibo.com/u/1261648152
我没收到微博私信。。。。或者你去公众号【Burpsuite实战教程】联系我，3ks
